spring:
  application:
    name: job-service
  datasource:
    initial-size: 3
    max-active: 25
    password: i_hate_cs462
    test-on-borrow: true
    url: jdbc:mysql://cs462-final-project-db-3.cyacdms6sqds.us-west-2.rds.amazonaws.com:3306/jobs
    username: root
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
urls:
  scheme: http://
  hosts:
    job: ec2-52-36-117-25.us-west-2.compute.amazonaws.com
    message: ec2-34-212-183-115.us-west-2.compute.amazonaws.com
    user: ec2-34-211-205-116.us-west-2.compute.amazonaws.com
  port: 8080
  self: ${urls.scheme}${urls.hosts.job}:${urls.port}
  service:
    job: ${urls.scheme}${urls.hosts.job}:${urls.port}
    message: ${urls.scheme}${urls.hosts.message}:${urls.port}
    user: ${urls.scheme}${urls.hosts.user}:${urls.port}