logging:
  level:
    com.volleymetrics: DEBUG
server:
  port: 6301
urls:
  localhost: http://localhost
  self: ${urls.localhost}:6301
  service:
    job: ${urls.localhost}:6301
#    message: ${urls.localhost}:6303
#    user: ${urls.localhost}:6302