spring:
  application:
    name: job-service
  datasource:
    initial-size: 3
    max-active: 25
    password: i_hate_cs462
    test-on-borrow: true
    url: jdbc:mysql://cs462-final-project-db-3.cyacdms6sqds.us-west-2.rds.amazonaws.com:3306/jobs
    username: root
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect